"""add_deleted_at_to_report

Revision ID: fa2fc15caf98
Revises: 006_add_report_inference_fields
Create Date: 2026-05-02 07:59:01.693268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2fc15caf98'
down_revision: Union[str, None] = '006_add_report_inference_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'deleted_at')
    # ### end Alembic commands ###
